### ISSUE TITLE
Infografia_librerias

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/infografia-de-las-librerias-CxrlosMX#2]
![Infografia_Componentes y librerias](https://user-images.githubusercontent.com/77459857/114485989-8adb5700-9bd2-11eb-98c1-2a65bc365db7.jpg)
[Infografia_Componentes y librerias.jpg.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-CxrlosMX/files/6300760/Infografia_Componentes.y.librerias.jpg.pdf)

**Comment by MLR062998** [comment]
20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
